window.SPOTS = [

  /* ─── TEMPLES ─────────────────────────────────────────── */
  {
    id: "sengakuji",
    name: "Sengaku-ji Temple", nameJP: "泉岳寺",
    category: "temple", emoji: "🏛️",
    address: "2-11-1 Takanawa, Minato-ku",
    lat: 35.6377, lng: 139.7364,
    walk: "12 min walk", walkJP: "徒歩12分",
    hours: { 0:[[700,1600]], 1:[[700,1600]], 2:[[700,1600]], 3:[[700,1600]], 4:[[700,1600]], 5:[[700,1600]], 6:[[700,1600]] },
    hoursNote: "Museum open same hours (¥500 entry)",
    hoursNoteJP: "境内の博物館も同時間 (入館料¥500)",
    googleRating: 4.3, googleReviews: 4051,
    googleMapsUrl: "https://maps.google.com/?q=Sengakuji+Temple+Tokyo",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null,
    website: "https://sengakuji.or.jp/",
    cuisine: null, cuisineJP: null, budget: null,
    desc: "A Soto Zen temple founded in 1612 by Tokugawa Ieyasu. Famous as the resting place of the 47 Ronin — Japan's most celebrated samurai loyalty story. The small museum (¥500) holds swords, scrolls, and personal effects of the ronin. Incense sticks available at the gate.",
    descJP: "1612年、徳川家康によって建立された曹洞宗の寺院。忠義の武士として日本中で称えられる「四十七士」の墓所として有名です。小さな博物館（入館料500円）には刀剣や巻物、義士ゆかりの品々が展示されています。山門前で線香を購入できます。",
    tip: "Visit on December 14 for the Gishi Festival — one of Tokyo's most atmospheric annual events.",
    tipJP: "12月14日の義士祭は東京で最も情緒あるお祭りのひとつ。ぜひ訪れてみてください。",
    ownerPick: false,
    photo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Sengakuji_temple_-_IMG_6402.JPG",
  },
  {
    id: "koyasan",
    name: "Koyasan Tokyo Betsuin", nameJP: "高野山東京別院",
    category: "temple", emoji: "🏛️",
    address: "3-15-18 Takanawa, Minato-ku",
    lat: 35.6350, lng: 139.7340,
    walk: "5 min walk", walkJP: "徒歩5分",
    hours: { 0:[[900,1700]], 1:[[900,1700]], 2:[[900,1700]], 3:[[900,1700]], 4:[[900,1700]], 5:[[900,1700]], 6:[[900,1700]] },
    hoursNote: null, hoursNoteJP: null,
    googleRating: 4.3, googleReviews: 862,
    googleMapsUrl: "https://maps.google.com/?q=Koyasan+Tokyo+Betsuin",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null,
    website: "https://www.musubidaishi.jp/",
    cuisine: null, cuisineJP: null, budget: null,
    desc: "Tokyo branch of the famous Koyasan (Mt. Koya) Shingon Buddhist headquarters. Serene grounds with statues linked to the 88-temple Shikoku Pilgrimage. A peaceful escape and a rare chance to experience esoteric Buddhism in central Tokyo.",
    descJP: "和歌山・高野山を本山とする真言宗の東京別院。四国八十八ヶ所霊場ゆかりの石仏が並ぶ静寂な境内。都心にいながら、密教の世界に触れられる貴重な場所です。",
    tip: "A short detour from the main road reveals the stone lantern path — beautiful at dusk.",
    tipJP: "大通りから少し入ると石灯篭が並ぶ小径があります。夕暮れ時が格別の雰囲気です。",
    ownerPick: false,
    photo: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Koyasan_Tokyo_Betsuin_001.jpg",
  },
  {
    id: "kakurinji",
    name: "Kakurin-ji (Kiyomasa-sama)", nameJP: "覚林寺（清正公）",
    category: "temple", emoji: "🏛️",
    address: "1-1-47 Shirokanedai, Minato-ku",
    lat: 35.6397, lng: 139.7317,
    walk: "10 min walk", walkJP: "徒歩10分",
    hours: { 0:[[900,1700]], 1:[[900,1700]], 2:[[900,1700]], 3:[[900,1700]], 4:[[900,1700]], 5:[[900,1700]], 6:[[900,1700]] },
    hoursNote: null, hoursNoteJP: null,
    googleRating: 4.0, googleReviews: 272,
    googleMapsUrl: "https://maps.google.com/?q=Kakurinji+Shirokanedai",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null,
    website: null,
    cuisine: null, cuisineJP: null, budget: null,
    desc: "A Nichiren sect temple founded in 1631, beloved locally as 'Kiyomasa-sama' — dedicated to the legendary warlord Kato Kiyomasa. Collect a goshuin (temple stamp) here and browse competition-victory charms popular with athletes and performers.",
    descJP: "1631年創建の日蓮宗の寺院。地元では「清正公さま」として親しまれ、戦国武将・加藤清正を祀っています。必勝祈願のお守りはアスリートや芸能関係者に人気。御朱印はその場で手書きしていただけます。",
    tip: "Quiet on weekday mornings; the goshuin is handwritten on the spot.",
    tipJP: "平日の朝は静かで穴場。御朱印は丁寧に手書きしていただけます。",
    ownerPick: false,
    photo: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Kakurinji_Temple_Main_Hall_20150725.JPG",
  },

  /* ─── LANDMARKS ────────────────────────────────────────── */
  {
    id: "prince-garden",
    name: "Prince Hotel Japanese Garden", nameJP: "グランドプリンスホテル高輪 日本庭園",
    category: "landmark", emoji: "🌲",
    address: "3-13-1 Takanawa, Minato-ku",
    lat: 35.6311, lng: 139.7345,
    walk: "8 min walk", walkJP: "徒歩8分",
    hours: { 0:[[900,2100]], 1:[[900,2100]], 2:[[900,2100]], 3:[[900,2100]], 4:[[900,2100]], 5:[[900,2100]], 6:[[900,2100]] },
    hoursNote: "Evening light-up from 18:00",
    hoursNoteJP: "18:00からライトアップ",
    googleRating: 4.5, googleReviews: 133,
    googleMapsUrl: "https://maps.google.com/?q=Prince+Hotel+Japanese+Garden+Takanawa",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null,
    website: "https://www.princehotels.co.jp/takanawa/",
    cuisine: null, cuisineJP: null, budget: null,
    desc: "A meticulously maintained traditional Japanese garden set within the Grand Prince Hotel Takanawa grounds. Especially magical after dark when colored LED lighting illuminates stone lanterns and the pond. Cherry blossoms in spring draw visitors from across Tokyo.",
    descJP: "グランドプリンスホテル高輪の敷地内にある精緻な日本庭園。夜になると石灯篭と池をカラフルなLEDが照らし、幻想的な雰囲気に。春の桜の季節は都内各地からの来訪者で賑わいます。",
    tip: "Evening visits (after 18:00) offer the most dramatic lighting. Open to the public.",
    tipJP: "18時以降のライトアップが最も美しい。一般公開されています。",
    ownerPick: false,
    photo: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Grand_Prince_Hotel_Takanawa_garden_-_IMG_6375.JPG",
  },
  {
    id: "gateway-city",
    name: "Takanawa Gateway City", nameJP: "高輪ゲートウェイシティ",
    category: "landmark", emoji: "🏢",
    address: "2-21-21 Takanawa, Minato-ku",
    lat: 35.6357, lng: 139.7402,
    walk: "15 min walk / 2 stops by train", walkJP: "徒歩15分 / 電車2駅",
    hours: { 0:[[1100,2100]], 1:[[1100,2100]], 2:[[1100,2100]], 3:[[1100,2100]], 4:[[1100,2100]], 5:[[1100,2100]], 6:[[1100,2100]] },
    hoursNote: "Individual shops & restaurants may vary",
    hoursNoteJP: "店舗・レストランによって異なります",
    googleRating: 4.0, googleReviews: 619,
    googleMapsUrl: "https://maps.google.com/?q=Takanawa+Gateway+City",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null,
    website: "https://takanawa-gateway-city.jp/",
    cuisine: null, cuisineJP: null, budget: null,
    desc: "Tokyo's newest large-scale urban development, opened March 2025. Twin landmark towers by Kengo Kuma connect directly to Takanawa Gateway Station. Free observation deck with panoramic views of Tokyo and the Shinkansen tracks. High-end shops and diverse dining on upper floors.",
    descJP: "2025年3月に開業した東京最新の大型複合施設。建築家・隈研吾設計の双塔が高輪ゲートウェイ駅に直結。無料の展望台からは新幹線の線路越しに東京の絶景が広がります。上層階には個性豊かなショップとレストランが揃います。",
    tip: "Take the free observation deck elevator — views of Rainbow Bridge and Tokyo Tower are spectacular.",
    tipJP: "無料の展望台エレベーターへ。レインボーブリッジと東京タワーの眺めは圧巻です。",
    ownerPick: false,
    photo: "Foto/gateway-city/Takanawa Gateway City.webp",
  },
  {
    id: "tozenji",
    name: "Tozen-ji Temple (First British Legation Site)", nameJP: "東禅寺（初代英国公使館跡）",
    category: "temple", emoji: "🏛️",
    address: "3-16-16 Takanawa, Minato-ku",
    lat: 35.6335, lng: 139.7357,
    walk: "6 min walk", walkJP: "徒歩6分",
    hours: { 0:[[600,1800]], 1:[[600,1800]], 2:[[600,1800]], 3:[[600,1800]], 4:[[600,1800]], 5:[[600,1800]], 6:[[600,1800]] },
    hoursNote: "Grounds open sunrise to sunset",
    hoursNoteJP: "境内は日の出〜日の入り",
    googleRating: null, googleReviews: null,
    googleMapsUrl: "https://maps.google.com/?q=Tozenji+Temple+Takanawa",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null,
    website: null,
    cuisine: null, cuisineJP: null, budget: null,
    desc: "In the 1860s, this temple served as Japan's first British Legation — the site of dramatic samurai attacks on British diplomats during the turbulent Bakumatsu era. A three-tiered pagoda stands within the tranquil grounds. A hidden piece of Japan's modernisation history.",
    descJP: "1860年代、この寺院は日本初の英国公使館として使用されました。幕末の動乱の中、攘夷派の武士による英国外交官への襲撃事件が起きた歴史的な場所。境内には三重塔がそびえ、日本近代化の歴史の痕跡が静かに刻まれています。",
    tip: "Combined well with a walk to Sengaku-ji — both sit along the same hillside lane.",
    tipJP: "同じ丘の道沿いに泉岳寺もあり、セットで散歩するのに最適なコースです。",
    ownerPick: false,
    photo: "Foto/tozenji/Tozen-ji Temple (First British Legation Site).webp",
  },

  /* ─── SHRINES ───────────────────────────────────────────── */
  {
    id: "takayama-inari",
    name: "Takayama Inari Shrine", nameJP: "高山稲荷神社",
    category: "shrine", emoji: "⛩️",
    address: "4-5-8 Takanawa, Minato-ku",
    lat: 35.6273, lng: 139.7332,
    walk: "9 min walk", walkJP: "徒歩9分",
    hours: { 0:[[1100,1500]], 1:null, 2:[[1100,1500]], 3:null, 4:null, 5:[[1100,1500]], 6:[[1100,1500]] },
    hoursNote: "Open Tue/Sat/Sun only. New shrine building completed Dec 2025",
    hoursNoteJP: "火・土・日のみ。新社殿2025年12月完成",
    googleRating: 4.4, googleReviews: 9,
    googleMapsUrl: "https://maps.app.goo.gl/aoeGBpqasiBHq8cd9",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null,
    website: null,
    cuisine: null, cuisineJP: null, budget: null,
    desc: "A quietly beautiful Inari (fox deity) shrine relocated to higher ground on the Takanawa hillside. The new shrine building was completed in December 2025. A goshuin (hand-written calligraphic stamp) is available at the shrine office for ¥500 — a wonderful keepsake. Open Tuesday, Saturday, and Sunday only.",
    descJP: "高輪の丘の上に移転・再建された、狐神（お稲荷さん）を祀る美しい神社。新社殿は2025年12月に完成しました。御朱印所では500円で手書きの御朱印を授与（火・土・日のみ）。素敵な思い出の品になります。",
    tip: "Goshuin available Tue/Sat/Sun. Only ¥500 — a beautiful souvenir from one of Tokyo's lesser-known shrines.",
    tipJP: "御朱印は火・土・日のみ、500円。東京の知られざる神社でいただける素敵なお土産です。",
    ownerPick: false,
    photo: "Foto/takayama-inari/Takayama Inari Shrine.webp",
  },

  /* ─── RESTAURANTS ──────────────────────────────────────── */
  {
    id: "kiku-sushi",
    name: "Kiku Sushi", nameJP: "菊寿司",
    category: "restaurant", emoji: "🍣",
    address: "3-9-11 Takanawa, Minato-ku",
    lat: 35.6321, lng: 139.7319,
    walk: "2 min walk", walkJP: "徒歩2分",
    hours: { 0:null, 1:[[1130,1300],[1700,2130]], 2:[[1700,2130]], 3:[[1130,1300],[1700,2130]], 4:[[1130,1300],[1700,2130]], 5:[[1130,1300],[1700,2130]], 6:[[1700,2130]] },
    hoursNote: "Lunch Mon/Tue/Thu/Fri only",
    hoursNoteJP: "ランチは月・火・木・金のみ",
    googleRating: 4.2, googleReviews: 158,
    googleMapsUrl: "https://maps.google.com/?q=Kiku+Sushi+Takanawa",
    tabelog: "3.4", tabelogNote: "Neighbourhood sushi staple loved by locals", tabelogNoteJP: "地元民に愛される町の寿司店",
    instagram: null, website: null,
    cuisine: "Sushi / Japanese", cuisineJP: "寿司 / 和食",
    budget: "Lunch under ¥1,000 / Dinner ¥3,000–¥5,000",
    desc: "A proper neighbourhood sushi counter steps from the property. Super-fresh seasonal fish, generous lunch sets under ¥1,000, and attentive staff. English menu available. The toro nigiri and clam miso soup are standout.",
    descJP: "宿のすぐ近くにある本格的な寿司カウンター。旬の新鮮な魚、千円以下のランチセット、丁寧なスタッフが揃います。英語メニューあり。とろにぎりとあさりの味噌汁が絶品です。",
    tip: "Counter seats give the best experience. No reservation needed for lunch.",
    tipJP: "カウンター席が一番の醍醐味。ランチは予約不要です。",
    ownerPick: false,
    photo: "Foto/kiku-sushi/Kiku Sushi.webp",
  },
  {
    id: "danta",
    name: "Danta", nameJP: "段太",
    category: "restaurant", emoji: "🍺",
    address: "3-7-14 Takanawa, Minato-ku",
    lat: 35.6327, lng: 139.7317,
    walk: "3 min walk", walkJP: "徒歩3分",
    hours: { 0:null, 1:[[1730,2300]], 2:[[1730,2300]], 3:[[1730,2300]], 4:[[1730,2300]], 5:[[1730,2300]], 6:[[1730,2300]] },
    hoursNote: "Cash only",
    hoursNoteJP: "現金のみ",
    googleRating: 4.3, googleReviews: 291,
    googleMapsUrl: "https://maps.google.com/?q=Danta+Takanawa",
    tabelog: "3.5", tabelogNote: "Solid local izakaya, excellent gyoza", tabelogNoteJP: "安定のご近所居酒屋、餃子が絶品",
    instagram: null, website: null,
    cuisine: "Izakaya (Japanese pub dining)", cuisineJP: "居酒屋",
    budget: "¥2,000–¥3,500 / person with drinks",
    desc: "A beloved local izakaya with outstanding gyoza, perfectly crispy karaage, and cold beer. Cash-only, relaxed atmosphere, and English-speaking staff. This is the kind of place tourists rarely find — the real Tokyo after-work experience.",
    descJP: "地元で愛されるアットホームな居酒屋。絶品の餃子、カリカリのから揚げ、冷えたビールが揃います。現金のみ、リラックスした雰囲気で英語が話せるスタッフも。観光客がなかなかたどり着けない「本物の東京」体験。",
    tip: "Arrive by 18:00 for a seat without waiting. Cash only.",
    tipJP: "18時までに行けば待たずに座れます。現金のみ。",
    ownerPick: false,
    photo: "Foto/danta/Danta.webp",
  },
  {
    id: "il-calore",
    name: "IL CALORE", nameJP: "高輪 イルカローレ",
    category: "restaurant", emoji: "🍷",
    address: "3-9-20 Takanawa, Minato-ku (2F)",
    lat: 35.6325, lng: 139.7316,
    walk: "3 min walk", walkJP: "徒歩3分",
    hours: { 0:null, 1:[[1800,2330]], 2:[[1800,2330]], 3:[[1800,2330]], 4:[[1800,2330]], 5:[[1800,2330]], 6:[[1200,1430],[1800,2330]] },
    hoursNote: "Reservation essential — book 1+ week ahead",
    hoursNoteJP: "要予約 — 1週間以上前に",
    googleRating: 4.8, googleReviews: 18,
    googleMapsUrl: "https://maps.google.com/?q=IL+CALORE+Takanawa",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Italian (omakase course)", cuisineJP: "イタリアン（おまかせコース）",
    budget: "¥15,000–¥20,000 / person",
    desc: "An intimate 8-seat counter where one chef delivers a seasonal Italian omakase. Homemade tortellini with truffle, charcoal-grilled seafood, Japanese ingredients woven into classic Italian technique. One of Takanawa's best-kept secrets.",
    descJP: "8席のカウンターで一人のシェフが届ける季節のイタリアンおまかせコース。トリュフ入り手打ちトルテッリーニ、炭火焼き魚介、和の食材をイタリア料理の技法で昇華。高輪随一の隠れた名店。",
    tip: "Reservation essential — book at least one week ahead. A truly special evening.",
    tipJP: "要予約 — 1週間以上前に。特別な夜の演出にぜひ。",
    ownerPick: false,
    photo: "https://tblg.k-img.com/restaurant/images/Rvw/305178/640x640_rect_5bd1a4293917f06d6deb93048fac379e.jpg",
  },
  {
    id: "via-dei-pepi",
    name: "VIA DEI PEPI", nameJP: "ヴィア・デイ・ペピ",
    category: "restaurant", emoji: "🍷",
    address: "2-1-62 Takanawa, Minato-ku",
    lat: 35.6407, lng: 139.7377,
    walk: "10 min walk", walkJP: "徒歩10分",
    hours: { 0:[[1130,1500],[1700,2200]], 1:null, 2:[[1700,2200]], 3:null, 4:[[1700,2200]], 5:[[1700,2200]], 6:[[1130,1500],[1700,2200]] },
    hoursNote: "Closed Mon & Wed",
    hoursNoteJP: "月・水定休",
    googleRating: 4.2, googleReviews: 153,
    googleMapsUrl: "https://maps.google.com/?q=VIA+DEI+PEPI+Takanawa",
    tabelog: "3.6", tabelogNote: "High praise for Neapolitan-style pizza", tabelogNoteJP: "ナポリスタイルのピッツァが高評価",
    instagram: null, website: null,
    cuisine: "Italian (pizza & pasta)", cuisineJP: "イタリアン（ピッツァ・パスタ）",
    budget: "¥2,500–¥4,000 / person",
    desc: "Exceptional Neapolitan-style pizza and house-made pasta in a cosy neighbourhood trattoria. The balsamic salad and wood-fired pizza with chili oil have a cult following. Weekend lunch is great value.",
    descJP: "地元に愛される小さなトラットリア。本格ナポリ風ピッツァと自家製パスタが絶品。バルサミコのサラダとチリオイルのピッツァはファンも多い看板メニュー。週末ランチはお得感も大。",
    tip: "Walk-ins often possible at the counter. Ask the chef which pizza to order.",
    tipJP: "カウンターはウォークインも可能なことが多い。どのピッツァにするかシェフに相談してみて。",
    ownerPick: false,
    photo: "Foto/via-dei-pepi/VIA DEI PEPI.jpg",
  },
  {
    id: "yuzen",
    name: "Yuzen Takanawadai", nameJP: "由膳 高輪台",
    category: "restaurant", emoji: "🍺",
    address: "Near Takanawadai Station",
    lat: 35.6310, lng: 139.7298,
    walk: "4 min walk", walkJP: "徒歩4分",
    hours: { 0:null, 1:[[1800,2400]], 2:[[1800,2400]], 3:[[1800,2400]], 4:[[1800,2400]], 5:[[1800,2400]], 6:[[1800,2400]] },
    hoursNote: "Closed Sunday",
    hoursNoteJP: "日曜定休",
    googleRating: 4.0, googleReviews: 13,
    googleMapsUrl: "https://maps.google.com/?q=Yuzen+Takanawadai",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Creative Japanese / Izakaya", cuisineJP: "創作和食 / 居酒屋",
    budget: "¥3,000–¥5,000 / person with drinks",
    desc: "A hushed, dimly-lit neighbourhood bar and dining room with a welcoming proprietress. Creative Japanese-style small plates, rare shochu, and homemade dishes. A sanctuary for whiskey lovers seeking calm after sightseeing.",
    descJP: "穏やかな雰囲気の中、女将が出迎えてくれるご近所の居酒屋。創作和風の小皿料理、希少な焼酎、自家製料理が揃います。観光の疲れを癒す、ウィスキー好きにも嬉しい隠れ家。",
    tip: "Smoking permitted throughout. Perfect for a late-night nightcap.",
    tipJP: "全席喫煙可。深夜の一杯にも最適です。",
    ownerPick: false,
    photo: "Foto/yuzen/Yuzen Takanawadai.webp",
  },
  {
    id: "kokoharu",
    name: "Koharu", nameJP: "心温 こはる",
    category: "restaurant", emoji: "🍺",
    address: "2-12-19 Shirokanedai, Minato-ku",
    lat: 35.6327, lng: 139.7304,
    walk: "6 min walk", walkJP: "徒歩6分",
    hours: { 0:null, 1:[[1130,1330],[1800,2300]], 2:[[1130,1330],[1800,2300]], 3:[[1130,1330],[1800,2300]], 4:[[1130,1330],[1800,2300]], 5:[[1130,1330],[1800,2300]], 6:[[1800,2300]] },
    hoursNote: "Closed Sunday. No English menu — staff speaks basic English",
    hoursNoteJP: "日曜定休。英語メニューなし（基本英語OK）",
    googleRating: 4.5, googleReviews: 65,
    googleMapsUrl: "https://maps.app.goo.gl/jaoLFtjX4mPPyJLr5",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Japanese Izakaya", cuisineJP: "居酒屋",
    budget: "¥3,000–¥5,000 / person with drinks",
    desc: "A warm, intimate izakaya with charming owners who give excellent recommendations even without an English menu. Consistently praised by foreign visitors for its welcoming atmosphere and fresh, home-style cooking. Walk-ins welcome on weekdays.",
    descJP: "魅力的なオーナー夫妻が営む温かみのある小さな居酒屋。英語メニューはありませんが、外国人ゲストから「居心地がいい」と絶賛される接客と新鮮な家庭料理風の品々が人気。平日はウォークイン可。",
    tip: "No English menu — use Google Translate's camera or simply ask for the owner's recommendation.",
    tipJP: "英語メニューなし — Googleレンズのカメラ翻訳が便利。またはおまかせでどうぞ。",
    ownerPick: false,
    photo: "Foto/kokoharu/Koharu 心温 こはる.webp",
  },
  {
    id: "niioka",
    name: "Sake-Meshitei Niioka", nameJP: "酒飯亭にいおか",
    category: "restaurant", emoji: "🍺",
    address: "3-7-14 Takanawa, Minato-ku",
    lat: 35.6327, lng: 139.7317,
    walk: "3 min walk", walkJP: "徒歩3分",
    hours: { 0:null, 1:[[1130,1400],[1730,2200]], 2:[[1730,2200]], 3:[[1130,1400],[1730,2200]], 4:[[1730,2200]], 5:[[1130,1400],[1730,2200]], 6:[[1730,2200]] },
    hoursNote: "Closed Sunday. Lunch Mon/Wed/Fri only",
    hoursNoteJP: "日曜定休。ランチは月・水・金のみ",
    googleRating: 4.7, googleReviews: 54,
    googleMapsUrl: "https://maps.app.goo.gl/j2RaD2uDh1Dk5aMSA",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Japanese Izakaya / Sake bar", cuisineJP: "居酒屋 / 日本酒バー",
    budget: "¥3,500–¥6,000 / person with drinks",
    desc: "A beloved neighbourhood izakaya rated 4.7★ with 54 reviews. Run by a mother-and-son team, known for exceptional seafood dishes, an ever-rotating Japanese sake (nihonshu) and shochu selection, and an atmosphere that makes you want to return the very next night.",
    descJP: "4.7★、54件のレビューを誇る地元民御用達の居酒屋。母と息子のチームによる運営で、新鮮な魚介料理と、常に変わる日本酒・焼酎のラインナップが自慢。一度訪れると翌日もまた来たくなる雰囲気。",
    tip: "Reserve for dinner. The straw-grilled dishes and sake pairing are a highlight.",
    tipJP: "ディナーは予約推奨。藁焼きと日本酒のペアリングが最高です。",
    ownerPick: false,
    photo: "Foto/niioka/Sake-Meshitei Niioka.webp",
  },
  {
    id: "tool-kogeisha",
    name: "Tool Takanawa Kogeisha", nameJP: "Tool 高輪工藝舎",
    category: "restaurant", emoji: "🍳",
    address: "3-10-7 Takanawa, Minato-ku",
    lat: 35.6319, lng: 139.7324,
    walk: "2 min walk", walkJP: "徒歩2分",
    hours: { 0:[[800,1600]], 1:null, 2:[[800,1600]], 3:[[800,1600]], 4:[[800,1600]], 5:[[800,1600]], 6:[[800,1600]] },
    hoursNote: "Closed Monday. Breakfast & brunch only",
    hoursNoteJP: "月曜定休。朝食・ブランチのみ",
    googleRating: 4.8, googleReviews: 13,
    googleMapsUrl: "https://maps.app.goo.gl/Fx7FJgD9Suvt9JZH6",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Café / Bakery (breakfast & brunch)", cuisineJP: "カフェ / ベーカリー（朝食・ブランチ）",
    budget: "¥1,000–¥2,500 / person",
    desc: "A tiny neighbourhood café steps from the property, rated 4.8★. The croissants are the talk of the street — flaky, buttery, and made fresh each morning. Friendly owner, great coffee, and a relaxed craft-workshop atmosphere. Allergy accommodations available with advance notice.",
    descJP: "宿のすぐ近くにある口コミ4.8★の小さなカフェ。毎朝焼きたてのサクサクバタークロワッサンは近隣でも評判。フレンドリーなオーナー、上質なコーヒー、クラフトワークショップのような落ち着いた空間。アレルギーへの対応も要相談で可能。",
    tip: "Skip the hotel breakfast and come here instead — the croissants are unmissable.",
    tipJP: "ホテルの朝食を抜いてここへ。クロワッサンは絶対に外せない一品です。",
    ownerPick: false,
    photo: "Foto/tool-kogeisha/Tool Takanawa Kogeisha.webp",
  },
  {
    id: "sepia",
    name: "Sepia", nameJP: "セピア",
    category: "restaurant", emoji: "🍳",
    address: "2-26-8 Shirokanedai, Minato-ku",
    lat: 35.6320, lng: 139.7302,
    walk: "6 min walk", walkJP: "徒歩6分",
    hours: { 0:null, 1:[[930,2200]], 2:[[930,2200]], 3:[[930,2200]], 4:[[930,2200]], 5:[[930,2200]], 6:[[1100,1900]] },
    hoursNote: "Closed Sunday. Smoking permitted",
    hoursNoteJP: "日曜定休。全席喫煙可",
    googleRating: 3.9, googleReviews: 84,
    googleMapsUrl: "https://maps.app.goo.gl/SMYdT9rKJ2zawMg4A",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Café / Japanese diner", cuisineJP: "喫茶店 / 食堂",
    budget: "¥800–¥1,500 / person",
    desc: "A cosy, old-fashioned neighbourhood café with a loyal local following. Reasonably priced chicken curry, Napoli pasta, and a warm atmosphere. The owner appears gruff but is genuinely kind. A slice of classic Tokyo kissaten culture.",
    descJP: "地元の常連客に愛されるレトロな雰囲気の喫茶店。リーズナブルなチキンカレー、ナポリタン、温かな空気感が魅力。オーナーは無愛想に見えますが実は親切な人。昭和の東京「喫茶店文化」を体験できる場所です。",
    tip: "Great for a cheap, unhurried lunch or evening coffee. Cash-friendly prices.",
    tipJP: "安くてゆったりしたランチや夜のコーヒーに最適。現金優遇価格。",
    ownerPick: false,
    photo: "Foto/sepia/Sepia.jpg",
  },
  {
    id: "kaen",
    name: "Kaen (Takanawa)", nameJP: "華宴（高輪）",
    category: "restaurant", emoji: "🍳",
    address: "3-11-5 Takanawa, Minato-ku",
    lat: 35.6316, lng: 139.7305,
    walk: "4 min walk", walkJP: "徒歩4分",
    hours: { 0:[[1100,2300]], 1:[[1100,2300]], 2:[[1100,2300]], 3:[[1100,2300]], 4:[[1100,2300]], 5:[[1100,2300]], 6:[[1100,2300]] },
    hoursNote: "Open daily 11:00–23:00",
    hoursNoteJP: "毎日11:00〜23:00",
    googleRating: 3.5, googleReviews: 169,
    googleMapsUrl: "https://maps.app.goo.gl/Mb4SeX7dQWBNg5837",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Chinese", cuisineJP: "中華料理",
    budget: "¥900–¥2,500 / person",
    desc: "A neighbourhood Chinese restaurant near Takanawadai Station. Generous portions at very reasonable prices — the sanmamen noodles and fried rice set meals are popular at lunch. Open until 23:00, making it one of the latest kitchens in the area.",
    descJP: "高輪台駅近くにある昔ながらの中華料理店。ボリューム満点で手頃な価格の料理が揃い、ランチのサンマーメンや炒飯セットが人気。23時まで営業しているエリア屈指の「遅い時間に食べられるお店」。",
    tip: "Order a noodle dish and add a half-portion of fried rice (+¥300) for a filling meal.",
    tipJP: "麺類に半炒飯（+¥300）を追加すると、お腹いっぱいの満足感ある食事になります。",
    ownerPick: false,
    photo: "Foto/kaen/Kaen (Takanawa).jpg",
  },
  {
    id: "hagari",
    name: "Panetteria Hagari", nameJP: "PANETTERIA HAGARI",
    category: "restaurant", emoji: "🍳",
    address: "2-1-60 Takanawa, Minato-ku",
    lat: 35.6405, lng: 139.7376,
    walk: "12 min walk", walkJP: "徒歩12分",
    hours: { 0:[[1100,2000]], 1:null, 2:null, 3:null, 4:[[1100,1800]], 5:[[1100,2000]], 6:[[1100,2000]] },
    hoursNote: "Open Thu–Sun only",
    hoursNoteJP: "木〜日のみ営業",
    googleRating: 4.6, googleReviews: 47,
    googleMapsUrl: "https://maps.app.goo.gl/VWeJFBhwV52yL1FL6",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Bakery / Deli & desserts", cuisineJP: "ベーカリー / デリ",
    budget: "¥500–¥2,000 / person",
    desc: "A boutique bakery and deli open Thursday–Sunday only. Artisan baguettes (¥420), creative prepared dishes like green curry couscous, and handmade desserts. Unassuming from the street but completely worth seeking out — friendly staff happy to assist first-timers.",
    descJP: "木〜日のみ営業の小さなベーカリー＆デリ。職人が作るバゲット（¥420）、グリーンカレークスクスなどのデリ料理、手作りデザートが揃います。外観はシンプルですが中身は本物。スタッフも初めての方に丁寧に対応してくれます。",
    tip: "Thu–Sun only. The baguette for ¥420 feeds a family of three. Desserts sell out by afternoon.",
    tipJP: "木〜日のみ。¥420のバゲットは3人でも十分な量。デザートは午後には売り切れることが多いので早めに。",
    ownerPick: false,
    photo: "Foto/hagari/Panetteria Hagari.jpg",
  },
  {
    id: "toko-hanten",
    name: "Chinese Restaurant Toko Hanten", nameJP: "中國料理 東興飯店",
    category: "restaurant", emoji: "🍳",
    address: "2-14-17 Takanawa, Minato-ku",
    lat: 35.6355, lng: 139.7383,
    walk: "13 min walk", walkJP: "徒歩13分",
    hours: { 0:null, 1:[[1115,1430],[1800,2100]], 2:[[1115,1430],[1800,2100]], 3:[[1115,1430],[1800,2100]], 4:[[1115,1430],[1800,2100]], 5:[[1115,1430],[1800,2100]], 6:[[1115,1400]] },
    hoursNote: "Closed Sunday. Lunch only on Saturday",
    hoursNoteJP: "日曜定休。土曜はランチのみ",
    googleRating: 4.0, googleReviews: 189,
    googleMapsUrl: "https://maps.app.goo.gl/RQsEJf3U6k1ZM1jT9",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Chinese (vegan-friendly)", cuisineJP: "中華料理（ヴィーガン対応）",
    budget: "¥800–¥2,500 / person",
    desc: "A neighbourhood Chinese restaurant praised for its authentic Hong Kong/Taiwanese-style stir-fry with genuine 'wok hei' (smoky flavour). Notably vegan-friendly with excellent vegetarian options. Tenshinhan (crab omelette rice, ¥800) and tan-tan noodles are must-orders.",
    descJP: "本物の「鑊気（ウォークヘイ）」を持つ香港・台湾スタイルの炒め物が評判の中華料理店。ヴィーガン・ベジタリアンにも優しいメニューが充実。天津飯（¥800）と担々麺は必食です。",
    tip: "One of the best-value Chinese spots in the area. Ask about vegan dishes — the kitchen accommodates well.",
    tipJP: "エリア屈指のコスパ。ヴィーガン料理はキッチンが丁寧に対応してくれます。",
    ownerPick: false,
    photo: "Foto/toko-hanten/Chinese Restaurant Toko Hanten.jpg",
  },
  {
    id: "fuki-seimen",
    name: "Fuki Seimen Kenkyusho Gotanda", nameJP: "富喜製麺研究所 五反田店",
    category: "restaurant", emoji: "🍜",
    address: "1-13-9 Higashigotanda, Shinagawa-ku",
    lat: 35.6265, lng: 139.7245,
    walk: "15 min walk / 1 stop by train", walkJP: "徒歩15分 / 電車1駅",
    hours: { 0:[[1100,1600],[1800,2300]], 1:[[1100,1430],[1800,2930]], 2:[[1100,1430],[1800,2930]], 3:[[1100,1430],[1800,2930]], 4:[[1100,1430],[1800,2930]], 5:[[1100,1430],[1800,2930]], 6:[[1100,1430],[1800,2930]] },
    hoursNote: "Open late-night Mon–Sat until 5:30 AM",
    hoursNoteJP: "月〜土は朝5:30まで深夜営業",
    googleRating: 3.6, googleReviews: 222,
    googleMapsUrl: "https://maps.app.goo.gl/iCaw5qmveejuNH3Q8",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Ramen / Tsukemen (dipping noodles)", cuisineJP: "ラーメン / つけ麺",
    budget: "¥1,000–¥1,500 / person",
    desc: "A noodle shop from a Kumamoto factory brand, specialising in kelp-water tsukemen (dipping noodles). The bonito dipping sauce is rich and umami-packed. Open until 5:30 AM Monday–Saturday — a lifesaver for late-night cravings after the neighbourhood bars close.",
    descJP: "熊本の麺工場ブランドによるラーメン・つけ麺専門店。昆布水つけ麺「のどごし生つけそば」が名物で、鰹だしのつけ汁はコクと旨みが溢れます。月〜土は朝5時半まで営業。バーはしごの後にも頼りになる一軒。",
    tip: "Order the 'Nodogoshi Nama Tsukesoba' — silky kelp-water noodles with a rich dipping broth.",
    tipJP: "「のどごし生つけそば」がおすすめ。昆布水の滑らかな麺とリッチなつけ汁の組み合わせ。",
    ownerPick: false,
    photo: "https://tblg.k-img.com/restaurant/images/Rvw/364938/640x640_rect_47fc084dfaefa729f156720e41def7af.jpg",
  },
  {
    id: "naoshiro",
    name: "Naoki", nameJP: "直城",
    category: "restaurant", emoji: "🍳",
    address: "3-3-8 Takanawa, Minato-ku",
    lat: 35.6346, lng: 139.7323,
    walk: "7 min walk", walkJP: "徒歩7分",
    hours: { 0:[[1200,1400],[1800,2200]], 1:null, 2:[[1200,1400],[1800,2200]], 3:[[1200,1400],[1800,2200]], 4:[[1200,1400],[1800,2200]], 5:[[1200,1400],[1800,2200]], 6:[[1200,1400],[1800,2200]] },
    hoursNote: "Closed Monday",
    hoursNoteJP: "月曜定休",
    googleRating: 3.8, googleReviews: 62,
    googleMapsUrl: "https://maps.app.goo.gl/KutkdSNjggup34AZ9",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Chinese (refined neighbourhood style)", cuisineJP: "中華料理",
    budget: "¥1,300–¥4,000 / person",
    desc: "A stylish, café-interior Chinese restaurant tucked into a Takanawa backstreet. Refined flavours with a delicate hand — the bang-bang chicken with homemade sesame sauce and the green pepper pork stir-fry are recommended. A neighbourhood gem with a loyal local following.",
    descJP: "高輪の路地に佇む、カフェのような内装の洗練された中華料理店。繊細な味わいが持ち味で、自家製ごまダレの棒棒鶏と青椒肉絲がイチオシ。地元の常連客に支持される隠れた名店です。",
    tip: "Reservation recommended for dinner. The bang-bang chicken lunch (¥1,300) is a standout.",
    tipJP: "ディナーは予約推奨。棒棒鶏のランチ（¥1,300）は特に評判です。",
    ownerPick: false,
    photo: "Foto/naoshiro/Naoki.webp",
  },

  /* ─── BARS ─────────────────────────────────────────────── */
  {
    id: "46banchi",
    name: "46番地 Standing Bar & Tatami Lounge", nameJP: "46番地",
    category: "bar", emoji: "🍺",
    address: "4-13-7 Takanawa, Minato-ku",
    lat: 35.6269, lng: 139.7333,
    walk: "8 min walk", walkJP: "徒歩8分",
    hours: { 0:[[1900,2400]], 1:null, 2:[[1930,2400]], 3:[[1930,2400]], 4:[[1930,2400]], 5:[[1900,2400]], 6:[[1900,2400]] },
    hoursNote: "Closed Monday. Dogs welcome inside!",
    hoursNoteJP: "月曜定休。ワンちゃん同伴OK！",
    googleRating: 4.4, googleReviews: 27,
    googleMapsUrl: "https://maps.app.goo.gl/Lij8e9Se7F2u9DZn9",
    tabelog: "3.03", tabelogNote: "Beloved neighbourhood bar, dog-friendly", tabelogNoteJP: "地元に愛される犬同伴OKのバー",
    instagram: "https://www.instagram.com/takanawa46banchi",
    website: "https://www.instagram.com/takanawa46banchi",
    cuisine: "Bar / Standing bar & Tatami lounge", cuisineJP: "バー / 立ち飲み・座敷",
    budget: "¥2,000–¥4,000 / person with drinks",
    desc: "A one-of-a-kind neighbourhood bar run by your host. The ground floor is a standing bar buzzing with locals; head upstairs to the record lounge — a tatami space where you can pick out a vinyl record and enjoy drinks and food while the music plays. The master's Neapolitan spaghetti is legendary among regulars. Dog-friendly, beloved by locals and visiting overseas guests alike.",
    descJP: "宿のオーナーが営む、唯一無二のご近所バー。1階は地元の人たちで賑わう立ち飲みスペース。2階へ上がるとレコードラウンジ——座敷で好きなレコードを選び、音楽を聴きながら飲み食いできる特別な空間です。マスターのナポリタンは常連の間で伝説的な一皿。ワンちゃん同伴OK、地元民と海外ゲストの両方に愛されています。",
    tip: "Drop by on any evening — the owner's friendly personality means first-timers are instantly welcomed like regulars.",
    tipJP: "毎晩気軽に立ち寄れます。フレンドリーなオーナーが、初めての方もすぐに常連のように迎えてくれます。",
    ownerPick: true,
    tenant: {
      name: "La otaco", nameJP: "La otaco",
      emoji: "🌮",
      days: "Thu · Fri · Sat · Sun", daysJP: "木・金・土・日",
      hours: { 0:[[1100,1400],[1900,2200]], 1:null, 2:null, 3:null, 4:[[1100,1400]], 5:[[1100,1400]], 6:[[1100,1400],[1900,2200]] },
      hoursNote: "Dinner on Sat & Sun only",
      hoursNoteJP: "夜営業は土日のみ",
      desc: "A Mexican taco kitchen at 46番地, open Thursday through Sunday. The handmade tortillas and fresh, boldly flavoured fillings have earned a devoted local following. Pairs perfectly with drinks from the bar — on weekends the standing bar and tatami lounge are open at the same time.",
      descJP: "木〜日に46番地で営業するメキシカンタコス専門店。手作りトルティーヤと新鮮な食材を使ったタコスが地元の常連に愛されています。バーのドリンクとの相性も抜群。週末は立ち飲みスペース・レコードラウンジと同時営業です。",
      photo: "Foto/La otaco/Lao taco.jpg",
      instagram: "https://www.instagram.com/laotaco2022",
      googleMapsUrl: "https://maps.app.goo.gl/5G97hkmLAsWT7rBA9",
    },
    photo: "Foto/46banchi/46番地 Standing Bar & Tatami Lounge.webp",
  },
  {
    id: "natural-wine-sun",
    name: "Natural Wine & Craft Beer sun.", nameJP: "ナチュラルワインとクラフトビール sun.",
    category: "bar", emoji: "🍷",
    address: "2-25-13 Shirokanedai, Minato-ku",
    lat: 35.6325, lng: 139.7301,
    walk: "6 min walk", walkJP: "徒歩6分",
    hours: { 0:[[1700,2300]], 1:null, 2:[[1800,2300]], 3:[[1800,2300]], 4:[[1800,2300]], 5:[[1800,2300]], 6:[[1700,2300]] },
    hoursNote: "Closed Monday. Reservation recommended",
    hoursNoteJP: "月曜定休。予約推奨",
    googleRating: 4.8, googleReviews: 46,
    googleMapsUrl: "https://maps.app.goo.gl/orjLdfvfsE6jma2y5",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Wine Bar / Bistro (Japanese–Italian–Spanish fusion)", cuisineJP: "ワインバー / ビストロ（和伊西フュージョン）",
    budget: "¥4,000–¥7,000 / person",
    desc: "A tiny neighbourhood bistro serving Japanese–Italian–Spanish fusion tapas alongside an ever-changing craft beer and natural wine list. Google-rated 4.8★ — one of the highest-rated spots in the area. Groups of 9+ can reserve the whole restaurant. The cold eggplant and pasta carbonara are legendary.",
    descJP: "和・伊・スペインのフュージョン料理と常時変わるクラフトビール＆ナチュラルワインを楽しめる小さなビストロ。Google評価4.8★はエリア随一。9名以上の貸し切り予約も可。冷製ナスとカルボナーラは看板メニューです。",
    tip: "Reserve ahead — it fills fast. Ask staff to guide your beer/wine pairing.",
    tipJP: "予約必須 — すぐに満席になります。ビール・ワインのペアリングはスタッフに相談を。",
    ownerPick: false,
    photo: "https://tblg.k-img.com/resize/660x370c/restaurant/images/Rvw/246989/bfb1b612696880318586a5a3573bf0ff.jpg?token=74430e1&api=v2",
  },
  {
    id: "audex",
    name: "Odex Japan (Wine Garden)", nameJP: "㈱オーデックスジャパン",
    category: "bar", emoji: "🍷",
    address: "4-1-22 Takanawa, Minato-ku",
    lat: 35.6287, lng: 139.7315,
    walk: "9 min walk", walkJP: "徒歩9分",
    hours: { 0:null, 1:[[900,1700]], 2:[[900,1700]], 3:[[900,1700]], 4:[[900,1700]], 5:[[900,1700]], 6:[[1100,1600]] },
    hoursNote: "Closed Sunday. Wine tasting in the garden — casual drop-in welcome",
    hoursNoteJP: "日曜定休。庭でのワインテイスティング随時歓迎",
    googleRating: 4.3, googleReviews: 4,
    googleMapsUrl: "https://maps.app.goo.gl/oTPnKqsBNHRHHqNk9",
    tabelog: null, tabelogNote: null, tabelogNoteJP: null, instagram: null, website: null,
    cuisine: "Wine importer / tasting", cuisineJP: "ワインインポーター / テイスティング",
    budget: "¥1,000–¥3,000 / person",
    desc: "A wine importer with a relaxed garden space where you can taste and buy bottles selected by friendly, knowledgeable staff. Praised for making wine accessible without pretension. One of the more unusual and charming stops in the neighbourhood.",
    descJP: "ワインインポーターが運営する庭付きのリラックスした空間。知識豊富でフレンドリーなスタッフが選んだボトルを気負わず楽しめます。近所の中でも特に個性的な、魅力的な立ち寄りスポット。",
    tip: "No wine expertise needed — staff will guide you to the perfect bottle.",
    tipJP: "ワインの知識は不要。スタッフがあなたにぴったりの一本を選んでくれます。",
    ownerPick: false,
    photo: "Foto/audex/odex Japan (Wine Garden).webp",
  },

];
